
const data = {
    products:[
        {
            id:1,
            categories:'watch',
            img:'/img/Watch_3.jpeg',
            img_second:'/img/Watch_3_2.jpeg',
            img_third:'/img/Watch_3_3.jpg',
            title:'Watch',
            desc:'Series 5 SE',
            price: 530,
            short_description:'Companion watch, iOS support, AMOLED 1.78" screen (368x448, touch), pedometer, heart rate monitor, working time: 18 hours, case: aluminum, bracelet: fluoroelastomer.',
            description:'Cupertino, California — Apple today announced Apple Watch Series 5, debuting an Always-On Retina display that never sleeps, so it’s easy to see the time and other important information, without raising or tapping the display. New location features, from a built-in compass to current elevation, help users better navigate their day, while international emergency calling1 allows customers to call emergency services directly from Apple Watch in over 150 countries, even without iPhone nearby. Apple Watch Series 5 is available in a wider range of materials, including aluminum, stainless steel, ceramic and an all-new titanium. Combined with the power of watchOS 6, users are empowered to take charge of their health and fitness with new features like Cycle Tracking, the Noise app and Activity Trends. '
        },

        {
            id:2,
            categories:'Laptop',
            img:'/img/Laptop_1.jpeg',
            img_second:'/img/Laptop_1_2.jpg',
            img_third:'/img/Laptop_1_3.jpg',
            title:'Laptop Macbook',
            desc:'Silver - M1 pro',
            price: 3250,
            short_description:'14.2" 3024 x 1964 IPS, 120 Hz, Non-touch, Apple M1 Pro (8 cores), 16 GB, 512 GB SSD, Built-in graphics card, Mac OS, Cover color silver',
            description:'In our case, the model was equipped with a minimum amount of RAM, and the SoC was with a basic set of CPU and GPU cores. And the SSD capacity was only 512 GB. On the Apple website, such a configuration as of the beginning of 2022 cost almost 190 thousand rubles, whereas the top version tested earlier cost 595 thousand! However, it is more correct to compare models with an equal SSD volume, since it accounts for a significant part of the difference. So, if the initial performance configuration of the MacBook Pro 14" is equipped with a 1 TB SSD, then it will cost almost 210 thousand rubles (prices for the same period of time). And a MacBook Pro 16" with the most productive stuffing and the same 1 TB of storage will cost 375 thousand. Its still very significant. Well, the last option: add the most productive SoC and the maximum amount of RAM in the MacBook Pro 14" — and we get the price of 355 thousand rubles. That is, for an enlarged display, an additional payment of 20 thousand. But still, what will be the difference in real performance between the two polar',
        },
        {
            id:3,
            categories:'Headphones',
            img:'/img/Headphones.jpeg',
            img_second:'/img/Headphones_1_2.jpg',
            img_third:'/img/Headphones_1_3.jfif',
            title:'Headphones Marshall',
            desc:'Major IV',
            price: 50,
            short_description:'wireless headphones with microphone, overhead, portable, Bluetooth 5.0, 20- 200 Hz, swivel cups, fast charging, working time 40 h',
            description:'Meet the Major IV, Marshalls iconic headphones with over 80 hours of wireless playback, wireless charging and a new improved ergonomic design. With more than three full days of use, you dont have to worry about your headphones stopping working when you need them. Specially tuned dynamic drivers deliver roaring bass, smooth mids and brilliant treble for rich, unmatched sound that youll never want to turn off.',
        },
        {
            id:4,
            categories:'Headphones',
            img:'/img/Headphones_2.jpeg',
            img_second:'/img/Headphones_2_2.jpg',
            img_third:'T/img/Headphones_2_3.jpg',
            title:'Headphones JBL Tune',
            desc:'710BT',
            price: 100,
            short_description:'wireless headphones with microphone, monitor (covering), Portable, Bluetooth 5.0, NFC, 4-40000 Hz, Swivel cups/Folding headband, Fast charging, working time 38 h, 1.2 m cable, active noise reduction',
            description:'JBL Pure Bass Technology Wireless Bluetooth connection Battery life 50 hours Hands-free phone calls + voice assistants Multipoint connection Lightweight folding design Detachable audio cable',
        },
        {
            id:5,
            categories:'watch',
            img:'/img/Watch_2.jpeg',
            img_second:'/img/Watch_2_2.jpg',
            img_third:'/img/Watch_2_3.png',
            title:'Watch Samsung',
            desc:'Galaxy Watch4',
            price: 300,
            short_description:'companion watch, Android support, AMOLED 1.4" screen (450x450, touch), pedometer, heart rate monitor, working time: 1 day 16 hours, case: steel, bracelet: fluoroelastomer',
            description:'Measure how your body performs during a workout and check your heart rate level as you recover. With advanced index and interval training available on Galaxy Watch4, you can optimize your workouts and train for new performance goals. Interval Training Pre-set the duration, distance and number of sets for running and cycling interval workouts on your Galaxy Watch4. Then, follow the guide through high- and low-intensity training sessions on your wrist. Interval Training Pre-set the duration, distance and number of sets for running and cycling interval workouts on your Galaxy Watch4. Then, follow the guide through high- and low-intensity training sessions on your wrist.',
        },
        {
            id:6,
            categories:'Laptop',
            img:'/img/Laptop_2.jpg',
            img_second:'/img/Laptop_2_2.jpg',
            img_third:'/img/Laptop_2_3.jpg',
            title:'Laptop Xiaomi',
            desc:'Pro 14',
            price: 1000,
            short_description:'14.0" 2560 x 1600 IPS, 120 Hz, Non-touch, Intel Core i5 11300H 3100 MHz, 16 GB DDR4, 512 GB SSD, NVIDIA GeForce MX450 2 GB graphics card, Cover color silver',
            description:'With a clean and modern finish, made of pure metal to keep the equipment cool at all times and resistant to bumps, drops and scratches, the Xiaomi Redmibook 14 Pro laptop features a 14″ inch screen (which we’ll talk about in detail in a moment in the next section). The difference lies in the thin margins of the screen, with an excellent screen-to-space ratio, making the most of the available space and enhancing its appearance. 7) Screen of the Xiaomi Redmibook 14 Pro Laptop. As we advanced a moment ago, our favorite laptop features a 14″ inch screen. Although this time Xiaomi has taken out all his artillery.',
        },
        
    ],
};
export default data;