
const data = {
    products:[
        {
            id:1,
            categories:'watch',
            img:'/img/Watch_3.jpeg',
            img_second:'/img/Watch_3_2.jpeg',
            img_third:'/img/Watch_3_3.jpg',
            title:'Watch',
            desc:'Series 5 SE',
            price: 530,
            short_description:'Companion watch, iOS support, AMOLED 1.78" screen (368x448, touch), pedometer, heart rate monitor, working time: 18 hours, case: aluminum, bracelet: fluoroelastomer.',
            description:'Cupertino, California — Apple today announced Apple Watch Series 5, debuting an Always-On Retina display that never sleeps, so it’s easy to see the time and other important information, without raising or tapping the display. New location features, from a built-in compass to current elevation, help users better navigate their day, while international emergency calling1 allows customers to call emergency services directly from Apple Watch in over 150 countries, even without iPhone nearby. Apple Watch Series 5 is available in a wider range of materials, including aluminum, stainless steel, ceramic and an all-new titanium. Combined with the power of watchOS 6, users are empowered to take charge of their health and fitness with new features like Cycle Tracking, the Noise app and Activity Trends. '
        },

        {
            id:2,
            categories:'Laptop',
            img:'/img/Laptop_1.jpeg',
            img_second:'/img/Laptop_1_2.jpg',
            img_third:'/img/Laptop_1_3.jpg',
            title:'Laptop Macbook',
            desc:'Silver - M1 pro',
            price: 3250,
            short_description:'14.2" 3024 x 1964 IPS, 120 Hz, Non-touch, Apple M1 Pro (8 cores), 16 GB, 512 GB SSD, Built-in graphics card, Mac OS, Cover color silver',
            description:'TEST',
        },
        {
            id:3,
            categories:'Headphones',
            img:'/img/Headphones.jpeg',
            img_second:'TEST',
            img_third:'TEST',
            title:'Headphones Marshall',
            desc:'Major IV',
            price: 50,
            short_description:'wireless headphones with microphone, overhead, portable, Bluetooth 5.0, 20- 200 Hz, swivel cups, fast charging, working time 40 h',
            description:'TEST',
        },
        {
            id:4,
            categories:'Headphones',
            img:'/img/Headphones_2.jpeg',
            img_second:'TEST',
            img_third:'TEST',
            title:'Headphones JBL Tune',
            desc:'710BT',
            price: 100,
            short_description:'wireless headphones with microphone, monitor (covering), Portable, Bluetooth 5.0, NFC, 4-40000 Hz, Swivel cups/Folding headband, Fast charging, working time 38 h, 1.2 m cable, active noise reduction',
            description:'TEST',
        },
        {
            id:5,
            categories:'watch',
            img:'/img/Watch_2.jpeg',
            img_second:'TEST',
            img_third:'TEST',
            title:'Watch Samsung',
            desc:'Galaxy Watch4',
            price: 300,
            short_description:'companion watch, Android support, AMOLED 1.4" screen (450x450, touch), pedometer, heart rate monitor, working time: 1 day 16 hours, case: steel, bracelet: fluoroelastomer',
            description:'TEST',
        },
        {
            id:6,
            categories:'Laptop',
            img:'/img/Laptop_2.jpg',
            img_second:'/img/Laptop_2_2.jpg',
            img_third:'/img/Laptop_2_3.jpg',
            title:'Laptop Xiaomi',
            desc:'Pro 14',
            price: 1000,
            short_description:'14.0" 2560 x 1600 IPS, 120 Hz, Non-touch, Intel Core i5 11300H 3100 MHz, 16 GB DDR4, 512 GB SSD, NVIDIA GeForce MX450 2 GB graphics card, Cover color silver',
            description:'TEST',
        },
        
    ],
};
export default data;